[[constraint]]
  name = "github.com/apple/foundationdb"
#  version = "release-5.1"
  branch = "release-5.1"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.3.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.11"