dist: xenial
sudo: "required"

language: "go"

go:
- 1.11

env:
  global:
  - GO111MODULE=on
  matrix:
  - BUILD_TYPE=Tests
  - BUILD_TYPE=Contracts

script:
- |
  case "${BUILD_TYPE}" in
    Tests)
      make all
      ;;
    Contracts)
      make contracts
      ;;
    *)
      echo "Unknown BUILD_TYPE value"
      exit 1
  esac
