#
# https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md
#

sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
before_script:
  - cd ./software/smartContract
  - scripts/rpc.sh > /dev/null &
  - sleep 5
script:
  - npm run lint
  - npm run test
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
