version: "3"
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
  operator:
    image: erage/plasma_operator
    ports:
      - "3001:3001"
    environment:
      geth_host: http://ganache:8545