version: "3"
services:
  ganache:
    build:
      context: .
      dockerfile: docker/Dockerfile.blockchain
    ports:
      - "8545:8545"
  operator:
    build:
      context: .
      dockerfile: docker/Dockerfile.operator
    ports:
      - "3001:3001"
    environment:
      geth_host: http://ganache:8545
    restart: on-failure
    depends_on:
      - ganache
  verifier:
    build:
      context: .
      dockerfile: docker/Dockerfile.verifier
    ports:
    - "8080:8080"
    environment:
      geth_host: http://ganache:8545
      operator_host: http://operator:3001
    restart: on-failure
    depends_on:
      - operator
