FROM golang:1.11-alpine

RUN apk add --update --no-cache make linux-headers libc-dev gcc git gmp gmp-dev

RUN mkdir /app
ADD . /app/

WORKDIR /app/

ENV GO111MODULE=on
RUN make build/operator

EXPOSE 3001
EXPOSE 8545

CMD ["/app/target/operator_linux_x86_64"]
